In [1]:
import pandas as pd
import numpy as np
import re
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# **Custom implementation**

In [2]:
documents = ["Dog bites man.", "Man bites dog.", "Dog eats meat.", "Man eats food."]
processed_docs = [doc.lower().replace(".","") for doc in documents]
processed_docs

['dog bites man', 'man bites dog', 'dog eats meat', 'man eats food']

In [3]:
# Prepare word dictonary
vocab = {}
count = 0
for doc in processed_docs:
    for word in doc.split():
        if(word not in vocab):
            count = count + 1
            vocab[word] = count
print(vocab)

{'dog': 1, 'bites': 2, 'man': 3, 'eats': 4, 'meat': 5, 'food': 6}


In [4]:
def get_one_hot_encoded_vector(sometext):
    one_hot_vector = []
    for word in sometext.split():
        temp = [0]*len(vocab)
        if word in vocab:
            temp[vocab[word]-1] = 1
        one_hot_vector.append(temp)
    return one_hot_vector

In [5]:
print(processed_docs[1])
get_one_hot_encoded_vector(processed_docs[1])

man bites dog


[[0, 0, 1, 0, 0, 0], [0, 1, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0]]

In [6]:
get_one_hot_encoded_vector('dog bites man')

[[1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0]]

# **Scikit learn Implementation**

In [7]:
d1 = 'dog bites man'
d2 = 'man bites dog'
d3 = 'dog eats meat'
d4 = 'man eats food'

In [8]:
data = [d1.split(), d2.split(), d3.split(), d4.split()]
values = data[0]+data[1]+data[2]+data[3]
print("The data: ",values)

encoder = OneHotEncoder()

OneHotEncodedVector = encoder.fit_transform(data).toarray()
print(f'One hot encoded vector',OneHotEncodedVector)

The data:  ['dog', 'bites', 'man', 'man', 'bites', 'dog', 'dog', 'eats', 'meat', 'man', 'eats', 'food']
One hot encoded vector [[1. 0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 0. 1. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 0.]]
